version = 0.1

[default.deploy.parameters]
stack_name = "FacebookAPIService"
resolve_s3 = true
s3_prefix = "FacebookAPIService"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EntityServiceBindings=\"ieva_entity_service_bindings\" OrchestratorFunc=\"arn:aws:lambda:us-east-1:039612842158:function:ieva-posting-orchestrator-IevaPostingOrchestrator-LahsMOTUA6x2:$LATEST\""
image_repositories = []
